# fly.toml file generated for vimhelpbot on 2020-08-02T14:41:02+03:00

app = "vimhelpbot"


[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
